### ISSUE TITLE
isort server fails to start after vs code upgrade

### ISSUE THREAD

**Issue by Mapiarz** [microsoft/vscode-isort#204]
All was nice and dandy up until yesterday when I upgraded vs code from 1.72 something to 1.74.3. 

```
Traceback (most recent call last):
  File "/home/mapiarz/.vscode/extensions/ms-python.isort-2022.8.0/bundled/tool/server.py", line 40, in <module>
    import utils
  File "/home/mapiarz/.vscode/extensions/ms-python.isort-2022.8.0/bundled/tool/utils.py", line 33, in <module>
    for p in (as_list(site.getsitepackages()) + as_list(site.getusersitepackages()))
AttributeError: module 'site' has no attribute 'getsitepackages'
Error in atexit._run_exitfuncs:
TypeError: stop_all_processes() missing 1 required positional argument: 'self'
[Info  - 1:05:37 PM] Connection to server got closed. Server will restart.
```

Running Python 3.7.5 in a venv. Tried reinstalling all ms python extensions (python, pylance, isort) and code itself.

Any ideas?

**Comment by karthiknadig** [comment]
@Mapiarz this seems like an issue with `site` package in the python itself that is installed on your system. Two options, 1) you can upgrade to 3.7.9 or better upgrade to 3.11 (3.7 will soon be out of service). 2) Down grade the python extension to version [2022.16.1](https://github.com/microsoft/vscode-python/releases/tag/2022.16.1) , you can do this from extensions view. Click on gear ion and select install another version.

**Comment by Mapiarz** [comment]
Thanks @karthiknadig. I was able to upgrade our project to 3.11 and that has resolved the issue.
